apiVersion: apps/v1
kind: Deployment
metadata:
  name: assafabankingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assafabankingapp
  template:
    metadata:
      labels:
        app: assafabankingapp
    spec:
      containers:
      - name: assafabankingapp
        image: mouhy/bks:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: assafabankingapp-service
spec:
  selector:
    app: assafabankingapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
